=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/build-order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:import namespace="http://www.w3.org/XML/1998/namespace">
   <xs:annotation>
     <xs:documentation>
        The schemaLocation of the relevant file is
        "http://www.w3.org/2001/xml.xsd"; however,
        we don"t want to assume people are always
        connected to the "net when playing with this file.
     </xs:documentation>
   </xs:annotation>
 </xs:import>
   
 <xs:element name="build-orders">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="build-order" minOccurs="1" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element> 

 <xs:element name="build-order">
   <xs:complexType>
     <xs:choice minOccurs="0" maxOccurs="unbounded">
       <xs:element name="build">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
           </xs:sequence>
           <xs:attribute name="name" type="unit-type" use="required"/>
           <xs:attribute name="place" type="xs:string" use="required"/>
           <xs:attributeGroup ref="command-attributes"/>
         </xs:complexType>
       </xs:element>
       <xs:element name="invent">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
           </xs:sequence>
           <xs:attribute name="name" type="tech-type" use="required"/>
           <xs:attributeGroup ref="command-attributes"/>
         </xs:complexType>
       </xs:element>
       <xs:element name="upgrade">
         <xs:complexType>
            <xs:sequence>
              <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
           </xs:sequence>
           <xs:attribute name="name" type="upgrade-type" use="required"/>
           <xs:attribute name="level" type="xs:int" use="optional"/>
           <xs:attributeGroup ref="command-attributes"/>
         </xs:complexType>
       </xs:element>       
       <xs:element name="train">
         <xs:complexType>
           <xs:sequence>
             <xs:element ref="condition" minOccurs="0" maxOccurs="1" />
             <xs:element name="build" maxOccurs="unbounded">
               <xs:complexType>
                 <xs:attribute name="name" type="unit-type" use="required" />
                 <xs:attribute name="weight" type="xs:int" use="required" />
               </xs:complexType>
             </xs:element>
           </xs:sequence>
           <xs:attribute name="building" type="unit-type" use="required"/>
           <xs:attributeGroup ref="command-attributes"/>
         </xs:complexType>
       </xs:element>
     </xs:choice>
     <xs:attribute name="type" />
     <xs:attribute name="name" />
     <xs:attribute name="race" />
     <xs:attribute name="against" />
     <xs:attribute name="probability" />
   </xs:complexType>
  </xs:element>
  <xs:element name="condition">
   <xs:complexType>
     <xs:attribute name="type" type="xs:string" use="required"/>
     <xs:attribute name="population" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:attributeGroup name="command-attributes">
  <xs:attribute name="minimal-population" type="xs:string" use="optional"/>
  <xs:attribute name="priority" type="xs:string" use="optional"/>
</xs:attributeGroup>

<xs:simpleType name="tech-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Stim Packs"/>
    <xs:enumeration value="Lockdown"/>
    <xs:enumeration value="EMP Shockwave"/>
    <xs:enumeration value="Spider Mines"/>
    <xs:enumeration value="Scanner Sweep"/>
    <xs:enumeration value="Tank Siege Mode"/>
    <xs:enumeration value="Defensive Matrix"/>
    <xs:enumeration value="Irradiate"/>
    <xs:enumeration value="Yamato Gun"/>
    <xs:enumeration value="Cloaking Field"/>
    <xs:enumeration value="Personnel Cloaking"/>
    <xs:enumeration value="Burrowing"/>
    <xs:enumeration value="Infestation"/>
    <xs:enumeration value="Spawn Broodling"/>
    <xs:enumeration value="Dark Swarm"/>
    <xs:enumeration value="Plague"/>
    <xs:enumeration value="Consume"/>
    <xs:enumeration value="Ensnare"/>
    <xs:enumeration value="Parasite"/>
    <xs:enumeration value="Psionic Storm"/>
    <xs:enumeration value="Hallucination"/>
    <xs:enumeration value="Recall"/>
    <xs:enumeration value="Stasis Field"/>
    <xs:enumeration value="Archon Warp"/>
    <xs:enumeration value="Restoration"/>
    <xs:enumeration value="Disruption Web"/>
    <xs:enumeration value="Mind Control"/>
    <xs:enumeration value="Dark Archon Meld"/>
    <xs:enumeration value="Feedback"/>
    <xs:enumeration value="Optical Flare"/>
    <xs:enumeration value="Maelstrom "/>
    <xs:enumeration value="Lurker Aspect"/>
    <xs:enumeration value="Healing"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="upgrade-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Terran Infantry Armor"/>
    <xs:enumeration value="Terran Vehicle Plating"/>
    <xs:enumeration value="Terran Ship Plating"/>
    <xs:enumeration value="Zerg Carapace"/>
    <xs:enumeration value="Zerg Flyer Carapace"/>
    <xs:enumeration value="Protoss Armor"/>
    <xs:enumeration value="Protoss Plating"/>
    <xs:enumeration value="Terran Infantry Weapons"/>
    <xs:enumeration value="Terran Vehicle Weapons"/>
    <xs:enumeration value="Terran Ship Weapons"/>
    <xs:enumeration value="Zerg Melee Attacks"/>
    <xs:enumeration value="Zerg Missile Attacks"/>
    <xs:enumeration value="Zerg Flyer Attacks"/>
    <xs:enumeration value="Protoss Ground Weapons"/>
    <xs:enumeration value="Protoss Air Weapons"/>
    <xs:enumeration value="Protoss Plasma Shields"/>
    <xs:enumeration value="U-238 Shells"/>
    <xs:enumeration value="Ion Thrusters"/>
    <xs:enumeration value="Titan Reactor"/>
    <xs:enumeration value="Ocular Implants"/>
    <xs:enumeration value="Moebius Reactor"/>
    <xs:enumeration value="Apollo Reactor"/>
    <xs:enumeration value="Colossus Reactor"/>
    <xs:enumeration value="Ventral Sacs"/>
    <xs:enumeration value="Antennae"/>
    <xs:enumeration value="Pneumatized Carapace"/>
    <xs:enumeration value="Metabolic Boost"/>
    <xs:enumeration value="Adrenal Glands"/>
    <xs:enumeration value="Muscular Augments"/>
    <xs:enumeration value="Grooved Spines"/>
    <xs:enumeration value="Gamete Meiosis"/>
    <xs:enumeration value="Metasynaptic Node"/>
    <xs:enumeration value="Singularity Charge"/>
    <xs:enumeration value="Leg Enhancements"/>
    <xs:enumeration value="Scarab Damage"/>
    <xs:enumeration value="Reaver Capacity"/>
    <xs:enumeration value="Gravitic Drive"/>
    <xs:enumeration value="Sensor Array"/>
    <xs:enumeration value="Gravitic Boosters"/>
    <xs:enumeration value="Khaydarin Amulet"/>
    <xs:enumeration value="Apial Sensors"/>
    <xs:enumeration value="Gravitic Thrusters"/>
    <xs:enumeration value="Carrier Capacity"/>
    <xs:enumeration value="Khaydarin Core"/>
    <xs:enumeration value="Argus Jewel"/>
    <xs:enumeration value="Argus Talisman"/>
    <xs:enumeration value="Caduceus Reactor"/>
    <xs:enumeration value="Chitinous Plating"/>
    <xs:enumeration value="Anabolic Synthesis"/>
    <xs:enumeration value="Charon Booster"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="unit-type">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Terran Marine"/>
    <xs:enumeration value="Terran Ghost"/>
    <xs:enumeration value="Terran Vulture"/>
    <xs:enumeration value="Terran Goliath"/>
    <xs:enumeration value="Goliath Turret"/>
    <xs:enumeration value="Terran Siege Tank"/>
    <xs:enumeration value="Tank Turret"/>
    <xs:enumeration value="Terran SCV"/>
    <xs:enumeration value="Terran Wraith"/>
    <xs:enumeration value="Terran Science Vessel"/>
    <xs:enumeration value="Gui Montag"/>
    <xs:enumeration value="Terran Dropship"/>
    <xs:enumeration value="Terran Battlecruiser"/>
    <xs:enumeration value="Vulture Spider Mine"/>
    <xs:enumeration value="Nuclear Missile"/>
    <xs:enumeration value="Terran Civilian"/>
    <xs:enumeration value="Sarah Kerrigan"/>
    <xs:enumeration value="Alan Schezar"/>
    <xs:enumeration value="Alan Turret"/>
    <xs:enumeration value="Jim Raynor"/>
    <xs:enumeration value="Jim Raynor"/>
    <xs:enumeration value="Tom Kazansky"/>
    <xs:enumeration value="Magellan"/>
    <xs:enumeration value="Edmund Duke"/>
    <xs:enumeration value="Duke Turret"/>
    <xs:enumeration value="Edmund Duke"/>
    <xs:enumeration value="Duke Turret"/>
    <xs:enumeration value="Arcturus Mengsk"/>
    <xs:enumeration value="Hyperion"/>
    <xs:enumeration value="Norad II"/>
    <xs:enumeration value="Terran Siege Tank"/>
    <xs:enumeration value="Tank Turret"/>
    <xs:enumeration value="Terran Firebat"/>
    <xs:enumeration value="Scanner Sweep"/>
    <xs:enumeration value="Terran Medic"/>
    <xs:enumeration value="Zerg Larva"/>
    <xs:enumeration value="Zerg Egg"/>
    <xs:enumeration value="Zerg Zergling"/>
    <xs:enumeration value="Zerg Hydralisk"/>
    <xs:enumeration value="Zerg Ultralisk"/>
    <xs:enumeration value="Zerg Broodling"/>
    <xs:enumeration value="Zerg Drone"/>
    <xs:enumeration value="Zerg Overlord"/>
    <xs:enumeration value="Zerg Mutalisk"/>
    <xs:enumeration value="Zerg Guardian"/>
    <xs:enumeration value="Zerg Queen"/>
    <xs:enumeration value="Zerg Defiler"/>
    <xs:enumeration value="Zerg Scourge"/>
    <xs:enumeration value="Torrasque"/>
    <xs:enumeration value="Matriarch"/>
    <xs:enumeration value="Infested Terran"/>
    <xs:enumeration value="Infested Kerrigan"/>
    <xs:enumeration value="Unclean One"/>
    <xs:enumeration value="Hunter Killer"/>
    <xs:enumeration value="Devouring One"/>
    <xs:enumeration value="Kukulza"/>
    <xs:enumeration value="Kukulza"/>
    <xs:enumeration value="Yggdrasill"/>
    <xs:enumeration value="Terran Valkyrie"/>
    <xs:enumeration value="Cocoon"/>
    <xs:enumeration value="Protoss Corsair"/>
    <xs:enumeration value="Protoss Dark Templar"/>
    <xs:enumeration value="Zerg Devourer"/>
    <xs:enumeration value="Protoss Dark Archon"/>
    <xs:enumeration value="Protoss Probe"/>
    <xs:enumeration value="Protoss Zealot"/>
    <xs:enumeration value="Protoss Dragoon"/>
    <xs:enumeration value="Protoss High Templar"/>
    <xs:enumeration value="Protoss Archon"/>
    <xs:enumeration value="Protoss Shuttle"/>
    <xs:enumeration value="Protoss Scout"/>
    <xs:enumeration value="Protoss Arbiter"/>
    <xs:enumeration value="Protoss Carrier"/>
    <xs:enumeration value="Protoss Interceptor"/>
    <xs:enumeration value="Dark Templar"/>
    <xs:enumeration value="Zeratul"/>
    <xs:enumeration value="Tassadar/Zeratul"/>
    <xs:enumeration value="Fenix"/>
    <xs:enumeration value="Fenix"/>
    <xs:enumeration value="Tassadar"/>
    <xs:enumeration value="Mojo"/>
    <xs:enumeration value="Warbringer"/>
    <xs:enumeration value="Gantrithor"/>
    <xs:enumeration value="Protoss Reaver"/>
    <xs:enumeration value="Protoss Observer"/>
    <xs:enumeration value="Protoss Scarab"/>
    <xs:enumeration value="Danimoth"/>
    <xs:enumeration value="Aldaris"/>
    <xs:enumeration value="Artanis"/>
    <xs:enumeration value="Rhynadon"/>
    <xs:enumeration value="Bengalaas"/>
    <xs:enumeration value="Unused"/>
    <xs:enumeration value="Unused"/>
    <xs:enumeration value="Scantid"/>
    <xs:enumeration value="Kakaru"/>
    <xs:enumeration value="Ragnasaur"/>
    <xs:enumeration value="Ursadon"/>
    <xs:enumeration value="Zerg Lurker Egg"/>
    <xs:enumeration value="Raszagal"/>
    <xs:enumeration value="Samir Duran"/>
    <xs:enumeration value="Alexei Stukov"/>
    <xs:enumeration value="Map Revealer"/>
    <xs:enumeration value="Gerard DuGalle"/>
    <xs:enumeration value="Zerg Lurker"/>
    <xs:enumeration value="Infested Duran"/>
    <xs:enumeration value="Disruption Field"/>
    <xs:enumeration value="Terran Command Center"/>
    <xs:enumeration value="Terran Comsat Station"/>
    <xs:enumeration value="Terran Nuclear Silo"/>
    <xs:enumeration value="Terran Supply Depot"/>
    <xs:enumeration value="Terran Refinery"/>
    <xs:enumeration value="Terran Barracks"/>
    <xs:enumeration value="Terran Academy"/>
    <xs:enumeration value="Terran Factory"/>
    <xs:enumeration value="Terran Starport"/>
    <xs:enumeration value="Terran Control Tower"/>
    <xs:enumeration value="Terran Science Facility"/>
    <xs:enumeration value="Terran Covert Ops"/>
    <xs:enumeration value="Terran Physics Lab"/>
    <xs:enumeration value="Unused Terran Bldg"/>
    <xs:enumeration value="Terran Machine Shop"/>
    <xs:enumeration value="Unused Terran Bldg"/>
    <xs:enumeration value="Terran Engineering Bay"/>
    <xs:enumeration value="Terran Armory"/>
    <xs:enumeration value="Terran Missile Turret"/>
    <xs:enumeration value="Terran Bunker"/>
    <xs:enumeration value="Norad II"/>
    <xs:enumeration value="Ion Cannon"/>
    <xs:enumeration value="Uraj Crystal"/>
    <xs:enumeration value="Khalis Crystal"/>
    <xs:enumeration value="Infested Command Center"/>
    <xs:enumeration value="Zerg Hatchery"/>
    <xs:enumeration value="Zerg Lair"/>
    <xs:enumeration value="Zerg Hive"/>
    <xs:enumeration value="Zerg Nydus Canal"/>
    <xs:enumeration value="Zerg Hydralisk Den"/>
    <xs:enumeration value="Zerg Defiler Mound"/>
    <xs:enumeration value="Zerg Greater Spire"/>
    <xs:enumeration value="Zerg Queen's Nest"/>
    <xs:enumeration value="Zerg Evolution Chamber"/>
    <xs:enumeration value="Zerg Ultralisk Cavern"/>
    <xs:enumeration value="Zerg Spire"/>
    <xs:enumeration value="Zerg Spawning Pool"/>
    <xs:enumeration value="Zerg Creep Colony"/>
    <xs:enumeration value="Zerg Spore Colony"/>
    <xs:enumeration value="Unused Zerg Bldg"/>
    <xs:enumeration value="Zerg Sunken Colony"/>
    <xs:enumeration value="Zerg Overmind"/>
    <xs:enumeration value="Zerg Overmind"/>
    <xs:enumeration value="Zerg Extractor"/>
    <xs:enumeration value="Mature Crysalis"/>
    <xs:enumeration value="Zerg Cerebrate"/>
    <xs:enumeration value="Zerg Cerebrate Daggoth"/>
    <xs:enumeration value="Unused Zerg Bldg 5"/>
    <xs:enumeration value="Protoss Nexus"/>
    <xs:enumeration value="Protoss Robotics Facility"/>
    <xs:enumeration value="Protoss Pylon"/>
    <xs:enumeration value="Protoss Assimilator"/>
    <xs:enumeration value="Protoss Unused"/>
    <xs:enumeration value="Protoss Observatory"/>
    <xs:enumeration value="Protoss Gateway"/>
    <xs:enumeration value="Protoss Unused"/>
    <xs:enumeration value="Protoss Photon Cannon"/>
    <xs:enumeration value="Protoss Citadel of Adun"/>
    <xs:enumeration value="Protoss Cybernetics Core"/>
    <xs:enumeration value="Protoss Templar Archives"/>
    <xs:enumeration value="Protoss Forge"/>
    <xs:enumeration value="Protoss Stargate"/>
    <xs:enumeration value="Stasis Cell/Prison"/>
    <xs:enumeration value="Protoss Fleet Beacon"/>
    <xs:enumeration value="Protoss Arbiter Tribunal"/>
    <xs:enumeration value="Protoss Robotics Support Bay"/>
    <xs:enumeration value="Protoss Shield Battery"/>
    <xs:enumeration value="Khaydarin Crystal Formation"/>
    <xs:enumeration value="Protoss Temple"/>
    <xs:enumeration value="Xel'Naga Temple"/>
    <xs:enumeration value="Mineral Field"/>
    <xs:enumeration value="Mineral Field"/>
    <xs:enumeration value="Mineral Field"/>
    <xs:enumeration value="Cave"/>
    <xs:enumeration value="Cave-in"/>
    <xs:enumeration value="Cantina"/>
    <xs:enumeration value="Mining Platform"/>
    <xs:enumeration value="Independent Command Center"/>
    <xs:enumeration value="Independent Starport"/>
    <xs:enumeration value="Jump Gate"/>
    <xs:enumeration value="Ruins"/>
    <xs:enumeration value="Kyadarin Crystal Formation"/>
    <xs:enumeration value="Vespene Geyser"/>
    <xs:enumeration value="Warp Gate"/>
    <xs:enumeration value="Psi Disrupter"/>
    <xs:enumeration value="Zerg Marker"/>
    <xs:enumeration value="Terran Marker"/>
    <xs:enumeration value="Protoss Marker"/>
    <xs:enumeration value="Zerg Beacon"/>
    <xs:enumeration value="Terran Beacon"/>
    <xs:enumeration value="Protoss Beacon"/>
    <xs:enumeration value="Zerg Flag Beacon"/>
    <xs:enumeration value="Terran Flag Beacon"/>
    <xs:enumeration value="Protoss Flag Beacon"/>
    <xs:enumeration value="Power Generator"/>
    <xs:enumeration value="Overmind Cocoon"/>
    <xs:enumeration value="Dark Swarm"/>
    <xs:enumeration value="Floor Missile Trap"/>
    <xs:enumeration value="Floor Hatch (UNUSED)"/>
    <xs:enumeration value="Left Upper Level Door"/>
    <xs:enumeration value="Right Upper Level Door"/>
    <xs:enumeration value="Left Pit Door"/>
    <xs:enumeration value="Right Pit Door"/>
    <xs:enumeration value="Floor Gun Trap"/>
    <xs:enumeration value="Left Wall Missile Trap"/>
    <xs:enumeration value="Left Wall Flame Trap"/>
    <xs:enumeration value="Right Wall Missile Trap"/>
    <xs:enumeration value="Right Wall Flame Trap"/>
    <xs:enumeration value="Start Location"/>
    <xs:enumeration value="Flag"/>
    <xs:enumeration value="Young Chrysalis"/>
    <xs:enumeration value="Psi Emitter"/>
    <xs:enumeration value="Data Disc"/>
    <xs:enumeration value="Khaydarin Crystal"/>
    <xs:enumeration value="Mineral Chunk"/>
    <xs:enumeration value="Mineral Chunk"/>
    <xs:enumeration value="Vespene Orb"/>
    <xs:enumeration value="Vespene Orb"/>
    <xs:enumeration value="Vespene Sac"/>
    <xs:enumeration value="Vespene Sac"/>
    <xs:enumeration value="Vespene Tank"/>
    <xs:enumeration value="Vespene Tank"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/build-order/tvp.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="build-order.xsd">
  <include name="globals.xml" />
  <build-order type="root" name="Crazy mass marine against protoss" race="Terran" against="Protoss" weight="1">
    <call name="Standard terran scv building" />
    <train building="Terran Barracks" priority="5">
      <build name="Terran Marine" weight="12" />
      <build name="Terran Medic" weight="4" />
      <build name="Terran Firebat" weight="1" />
      <build name="Terran Ghost" weight="1" />
    </train>
    <build name="Terran Supply Depot" place="non-producting-3X2" minimal-population="8"/>
    <build name="Terran Barracks" place="barracks" minimal-population="11"/>
    <build name="Terran Barracks" place="barracks" minimal-population="13"/>
    <build name="Terran Supply Depot" place="non-producting-3X2" minimal-population="15"/>
    <register-exception name="Standard terran supply depot building" />
    <build name="Terran Command Center" place="natural-expansion" minimal-population="20"/>
    <build name="Terran Engineering Bay" place="engineering-bay" minimal-population="26"/>
    <build name="Terran Refinery" place="refinery" minimal-population="30"/>
    <build name="Terran Academy" place="non-producting-3X2" minimal-population="31"/>
    <build name="Terran Missile Turret" place="turret-entrance-expansion" minimal-population="32"/>
    <build name="Terran Barracks" place="barracks" minimal-population="33"/>
    <invent name="Stim Packs" minimal-population="35" priority="9"/>
    <build name="Terran Refinery" place="refinery-expansion" minimal-population="51"/>
    <upgrade name="U-238 Shells" minimal-population="35" priority="8"/>
    <build name="Terran Comsat Station" minimal-population="35" priority="7"/>
    <build name="Terran Comsat Station" minimal-population="35" priority="7"/>
    <build name="Terran Barracks" place="barracks" minimal-population="37"/>
    <upgrade name="Terran Infantry Armor" level="1" minimal-population="35" priority="6"/>
    <build name="Terran Factory" place="building-with-addon" minimal-population="45"/>
    <build name="Terran Barracks" place="barracks" minimal-population="50"/>
    <build name="Terran Starport" place="building-with-addon" minimal-population="60"/>
    <train building="Terran Starport" priority="6">
      <build name="Terran Science Vessel" weight="1">
        <condition type="formula" formula="4 - All(Terran Science Vessel)" />
      </build>
      <build name="Terran Dropship" weight="1">
        <condition type="equation" equation="All(Terran Dropship) < 2" />
      </build>
    </train>
    <upgrade name="Terran Infantry Armor" level="3" minimal-population="35" priority="6"/>
    <upgrade name="Terran Infantry Weapons" level="3" minimal-population="35" priority="6"/>
    <build name="Terran Command Center" place="second-expansion"/>
    <build name="Terran Science Facility" place="building-with-addon"/>
    <build name="Terran Control Tower"/>
    <build name="Terran Covert Ops" />
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="Lockdown" priority="6"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="EMP Shockwave" priority="9"/>
    <invent name="Personnel Cloaking" priority="5"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Nuclear Silo" priority="6"/>
    <train building="Terran Nuclear Silo" priority="6">
      <build name="Nuclear Missile" weight="1" />
    </train>
  </build-order>
      
  <build-order type="root" name="TvP Metal" race="Terran" against="Protoss" weight="1">
    <call name="Standard terran scv building" />
    <register-exception name="Standard terran supply depot building">
    <train building="Terran Barracks" priority="5">
      <build name="Terran Marine" weight="12" >
        <condition type="equation" equation="All(Terran Marine) < 5" />
      </build>
    </train>
    <train building="Terran Factory" priority="5">
      <build name="Terran Siege Tank" weight="2" />
      <build name="Terran Vulture" weight="2" />
      <build name="Terran Goliath" weight="1" />
    </train>    
    <build name="Terran Barracks" place="barracks" minimal-population="11"/>
    <build name="Terran Refinery" place="refinery" minimal-population="12"/>
    <build name="Terran Factory" place="building-with-addon" />
    <invent name="Spider Mines" priority="6"/>
    <invent name="Tank Siege Mode" priority="6"/>
    <upgrade name="Ion Thrusters" />
    <build name="Terran Machine Shop" />
    <build name="Terran Factory" place="building-with-addon" />
    <build name="Terran Machine Shop" />
    <build name="Terran Engineering Bay" place="engineering-bay" />
    <build name="Terran Command Center" place="natural-expansion" />
    <build name="Terran Missile Turret" place="turret-entrance-expansion" />
    <build name="Terran Factory" place="building-with-addon" />
    <build name="Terran Machine Shop" />
    <build name="Terran Factory" place="building-with-addon" />
    <build name="Terran Machine Shop" />
    <build name="Terran Armory" place="non-producting-3X2" />
    <build name="Terran Armory" place="non-producting-3X2" />
    <upgrade name="Terran Vehicle Plating" level="3" priority="6"/>
    <upgrade name="Terran Vehicle Weapons" level="3" priority="6"/>
    <build name="Terran Factory" place="building-with-addon" />
    <build name="Terran Machine Shop" />
    <build name="Terran Starport" place="building-with-addon" />
    <train building="Terran Starport" priority="6">
      <build name="Terran Science Vessel" weight="1">
        <condition type="equation" equation="All(Terran Science Vessel) < 2" />
      </build>
      <build name="Terran Dropship" weight="1">
        <condition type="equation" equation="All(Terran Dropship) < 2" />
      </build>
    </train>
    <build name="Terran Control Tower" />
    <build name="Terran Command Center" place="second-expansion" />
    <build name="Terran Science Facility" place="building-with-addon" />
    <build name="Terran Covert Ops" />
    <invent name="EMP Shockwave" priority="9"/>
    </train>
  </build-order>
</build-orders>

=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/build-order/globals.xml
<build-orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="build-order.xsd">
  <build-order type="function" name="Standard terran scv building">
    <train building="Terran Command Center" priority="10">
      <build name="Terran SCV" weight="1">
        <condition type="and">
          <condition type="formula" formula="ActiveMinerals*2 + All(Terran Refinery)*3 + InProgress(Terran Command Center)*10 + All(Terran Command Center)*3 - All(Terran SCV)" />
          <condition type="formula" formula="ConfigValue(max_count_of_workers) - All(Terran SCV)" />
        </condition>
      </build>
    </train>
  </build-order>
  <build-order type="function" name="Standard terran supply depot building">
    <condition type="and">
      <condition type="formula" formula="UsedSupply(Terran) + Factories(Terran)*2  - PlannedSupply(Terran)" />
      <condition type="formula" formula="200 - PlannedSupply(Terran)" />
    </condition>
    <build name="Terran Supply Depot" place="non-producting-3X2"/>
  </build-order>
  <build-order type="function" name="Standard protoss probe building">
    <train building="Protoss Nexus" priority="10">
      <build name="Protoss Probe" weight="1">
        <condition type="and">
          <condition type="formula" formula="ActiveMinerals*2 + All(Protoss Assimilator)*3 + InProgress(Protoss Nexus)*10 + All(Protoss Nexus)*3 - All(Protoss Probe)" />
          <condition type="formula" formula="ConfigValue(max_count_of_workers) - All(Protoss Probe)" />
        </condition>
      </build>
    </train>
  </build-order>  
</build-orders>

=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/build-order/tvz.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="build-order.xsd">
  <include name="globals.xml" />
  <build-order type="root" name="SK terran" race="Terran" against="Zerg" probability="100%">
    <call name="Standard terran scv building" />
    <train building="Terran Barracks" priority="5">
      <build name="Terran Marine" weight="12" />
      <build name="Terran Medic" weight="4" />
      <build name="Terran Firebat" weight="1" />
    </train>
    <build name="Terran Barracks" place="barracks" minimal-population="11"/>
    <build name="Terran Barracks" place="barracks" minimal-population="13"/>
    <build name="Terran Command Center" place="natural-expansion" minimal-population="20"/>
    <build name="Terran Refinery" place="refinery" minimal-population="30"/>
    <build name="Terran Academy" place="non-producting-3X2" minimal-population="31"/>
    <build name="Terran Engineering Bay" place="engineering-bay" minimal-population="26"/>
    <build name="Terran Barracks" place="barracks" minimal-population="33"/>
    <build name="Terran Refinery" place="refinery-expansion" minimal-population="51"/>
    <invent name="Stim Packs" minimal-population="35" priority="4"/>
    <upgrade name="U-238 Shells" minimal-population="35" priority="4"/>
    <build name="Terran Missile Turret" place="turret-entrance-expansion" minimal-population="32"/>
    <build name="Terran Comsat Station" minimal-population="35"/>
    <build name="Terran Comsat Station" minimal-population="35"/>
    <upgrade name="Terran Infantry Armor" level="1" minimal-population="35"/>
    <build name="Terran Factory" place="factory" minimal-population="45"/>
    <build name="Terran Barracks" place="barracks" minimal-population="50"/>
    <build name="Terran Starport" place="starport"/>
    <train building="Terran Starport">
      <build name="Terran Science Vessel" weight="1" />
    </train>
    <upgrade name="Terran Infantry Armor" level="3"/>
    <upgrade name="Terran Infantry Weapons" level="3"/>
    <build name="Terran Science Facility" place="science-facility"/>
    <build name="Terran Command Center" place="second-expansion"/>
    <build name="Terran Control Tower"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
    <invent name="Irradiate"/>
    <build name="Terran Barracks" place="barracks"/>
    <build name="Terran Barracks" place="barracks"/>
  </build-order>
</build-orders>
