=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/maps/map-info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:import namespace="http://www.w3.org/XML/1998/namespace">
   <xs:annotation>
     <xs:documentation>
        The schemaLocation of the relevant file is
        "http://www.w3.org/2001/xml.xsd"; however,
        we don"t want to assume people are always
        connected to the "net when playing with this file.
     </xs:documentation>
   </xs:annotation>
 </xs:import>
   
 <xs:element name="map-description">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="expansions"/>
       <xs:element ref="starting-positions"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element> 

 <xs:element name="expansions">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="expansion" minOccurs="1" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element>

  <xs:element name="expansion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="position"/>
      </xs:sequence>
       <xs:attribute name="id"  type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
 
  <xs:element name="position">
    <xs:complexType>
      <xs:attribute name="x" type="xs:integer" use="required" />
      <xs:attribute name="y" type="xs:integer" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="starting-positions">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="starting-position" minOccurs="1" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element>
 
 <xs:element name="starting-position">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="standard-building-placement" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
     <xs:attribute name="expansion-id" type="xs:string" use="required" />     
   </xs:complexType>
 </xs:element>
 
  <xs:element name="standard-building-placement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="build-position" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="position" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />              
            <xs:attribute name="width" type="xs:int" use="required" />
            <xs:attribute name="height" type="xs:int" use="required" />
            <xs:attribute name="shortcut" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bwapi/bwapi/bwapi/bwapi-data/maps/ICCup Python 1.3.scx.xml
<?xml version="1.0" encoding="UTF-8"?>

<map-description xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	               xsi:noNamespaceSchemaLocation='map-info.xsd'>
  <expansions>
    <expansion id="12 o'clock">
      <position x="2720" y="240"/>
    </expansion>
    <expansion id="12 oclock' natural">
      <position x="1600" y="272"/>
    </expansion>
    <expansion id="9 o'clock">
      <position x="320" y="2768"/>
    </expansion>
    <expansion id="9 o'clock natural">
      <position x="288" y="1872"/>
    </expansion>
    <expansion id="6 o'clock">
      <position x="1408" y="3856"/>
    </expansion>
    <expansion id="6 o'clock natural">
      <position x="2464" y="3824"/>
    </expansion>
    <expansion id="3 o'clock">
      <position x="3776" y="1328"/>
    </expansion>
    <expansion id="3 o'clock natural">
      <position x="3808" y="2160"/>
    </expansion>
    <expansion id="top-left">
      <position x="288" y="240"/>
    </expansion>
    <expansion id="bottom-right">
      <position x="3808" y="3824"/>
    </expansion>
  </expansions>
  <starting-positions>
    
    <starting-position expansion-id="3 o'clock" >
      <standard-building-placement>
        <non-producting-3x2>
          <position x="125" y="25"/>
          <position x="125" y="27"/>
          <position x="125" y="29"/>
          <position x="125" y="31"/>
          <position x="125" y="33"/>
          <position x="125" y="29"/>
          <position x="122" y="25"/>
          <position x="122" y="27"/>
          <position x="122" y="29"/>
          <position x="122" y="31"/>
          <position x="122" y="33"/>
        </non-producting-3x2>
      </standard-building-placement>
    </starting-position>
    <starting-position expansion-id="6 o'clock">
     <standard-building-placement>
        <non-producting-3x2>
          <position x="26" y="122"/>
          <position x="26" y="120"/>
          <position x="26" y="118"/>
          <position x="26" y="116"/>
          <position x="29" y="122"/>
          <position x="29" y="120"/>
          <position x="29" y="118"/>
          <position x="29" y="116"/>
          <position x="28" y="124"/>
          <position x="31" y="124"/>
        </non-producting-3x2>
      </standard-building-placement>
    </starting-position>
    <starting-position expansion-id="9 o'clock" >
      <standard-building-placement>
        <non-producting-3x2>
          <position x="0" y="100"/>
          <position x="0" y="98"/>
          <position x="0" y="96"/>
          <position x="0" y="94"/>
          <position x="0" y="92"/>
          <position x="3" y="100"/>
          <position x="3" y="98"/>
          <position x="3" y="96"/>
          <position x="3" y="94"/>
          <position x="3" y="92"/>
        </non-producting-3x2>
      </standard-building-placement>
    </starting-position>
    <starting-position expansion-id="12 o'clock">
      <standard-building-placement>
        <non-producting-3x2>
          <position x="60" y="0"/>
          <position x="60" y="2"/>
          <position x="63" y="0"/>
          <position x="63" y="2"/>
          <position x="66" y="0"/>
          <position x="66" y="2"/>
          <position x="69" y="0"/>
          <position x="69" y="2"/>
          <position x="64" y="4"/>
          <position x="67" y="4"/>
        </non-producting-3x2>
      </standard-building-placement>
    </starting-position>
  </starting-positions>
</map-description>

=== bwapi/bwapi/bwapi/starcraft-folder/bwapi-data/maps/ICCup Longinus.scx.xml
<?xml version="1.0" encoding="UTF-8"?>

<map-description xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	               xsi:noNamespaceSchemaLocation="map-info.xsd">
  <expansions>
    <expansion id="12 oclock double">
      <position x="2528" y="192"/>
    </expansion>
    <expansion id="11 oclock natural">
      <position x="1184" y="192"/>
    </expansion>
    <expansion id="11 oclock">
      <position x="256" y="352"/>
    </expansion>
    <expansion id="9 oclock double">
      <position x="256" y="2016"/>
    </expansion>
    <expansion id="8 oclock natural">
      <position x="224" y="3136"/>
    </expansion>
    <expansion id="7 oclock">
      <position x="960" y="3744"/>
    </expansion>
    <expansion id="5 oclock double">
      <position x="2912" y="3360"/>
    </expansion>
    <expansion id="3 oclock natural">
      <position x="3712" y="2400"/>
    </expansion>
    <expansion id="2 oclock">
      <position x="3712" y="1504"/>
    </expansion>
    <expansion id="10 oclock onlymin">
      <position x="992" y="1120"/>
    </expansion>
    <expansion id="7 oclock onlymin">
      <position x="1376" y="3136"/>
    </expansion>
    <expansion id="2 oclock onlymin">
      <position x="2848" y="1824"/>
    </expansion>
  </expansions>
  <starting-positions>
    <starting-position expansion-id="11 oclock" >
      <standard-building-placement>
        <build-position name="non-producting-3X2" width="3" height="2">
          <position x="0" y="2"/>
          <position x="6" y="1"/>
          <position x="2" y="6"/>
          <position x="3" y="2"/>
          <position x="2" y="4"/>
          <position x="6" y="3"/>
          <position x="6" y="19"/>
          <position x="0" y="19"/>
          <position x="6" y="22"/>
          <position x="0" y="22"/>
          <position x="6" y="25"/>
          <position x="0" y="25"/>
          <position x="3" y="19"/>
          <position x="6" y="28"/>
          <position x="0" y="28"/>
          <position x="3" y="22"/>
          <position x="10" y="2"/>
          <position x="3" y="25"/>
          <position x="10" y="4"/>
          <position x="3" y="28"/>
          <position x="23" y="0"/>
          <position x="17" y="0"/>
          <position x="10" y="31"/>
          <position x="20" y="0"/>
        </build-position>
        <build-position name="barracks" width="4" height="3" shortcut="BB">
          <position x="23" y="9"/>
          <position x="23" y="12"/>
          <position x="23" y="15"/>
          <position x="19" y="9"/>
          <position x="19" y="12"/>
          <position x="19" y="15"/>
        </build-position>
        <build-position name="engineering-bay" width="4" height="3" shortcut="BE">
          <position x="24" y="4"/>
        </build-position>
        <build-position name="natural-expansion" width="4" height="3" shortcut="Ex">
          <position x="37" y="6"/>
        </build-position>
        <build-position name="refinery" width="4" height="2" shortcut="BR">
          <position x="8" y="6"/>
        </build-position>
        <build-position name="academy" width="3" height="2">
          <position x="21" y="4"/>
        </build-position>
        <build-position name="turret-entrance-expansion" width="2" height="2">
          <position x="44" y="11"/>
        </build-position>
      </standard-building-placement>
    </starting-position>
    <starting-position expansion-id="7 oclock">
     <standard-building-placement>
        <build-position name="non-producting-3X2" width="3" height="2">
          <position x="32" y="125"/>
          <position x="40" y="122"/>
          <position x="38" y="125"/>
          <position x="46" y="122"/>
          <position x="35" y="125"/>
          <position x="44" y="120"/>
          <position x="41" y="117"/>
          <position x="44" y="125"/>
          <position x="44" y="115"/>
          <position x="47" y="117"/>
          <position x="41" y="120"/>
          <position x="41" y="125"/>
          <position x="43" y="122"/>
          <position x="49" y="122"/>
          <position x="44" y="117"/>
          <position x="41" y="115"/>
          <position x="47" y="125"/>
          <position x="47" y="120"/>
          <position x="47" y="115"/>
          <position x="43" y="112"/>
          <position x="42" y="109"/>
          <position x="49" y="112"/>
          <position x="45" y="109"/>
          <position x="46" y="112"/>
        </build-position>
        <build-position name="barracks" width="4" height="3" shortcut="BB">
          <position x="12" y="111"/>
          <position x="16" y="111"/>
          <position x="12" y="114"/>
          <position x="16" y="114"/>
          <position x="12" y="117"/>
          <position x="16" y="117"/>
        </build-position>
        <build-position name="natural-expansion" width="4" height="3" shortcut="Ex">
          <position x="7" y="98"/>
        </build-position>
        <build-position name="engineering-bay" width="4" height="3" shortcut="BE">
          <position x="0" y="117"/>
        </build-position>
        <build-position name="refinery" width="4" height="2" shortcut="BR">
          <position x="23" y="118"/>
        </build-position>
        <build-position name="academy" width="3" height="2">
          <position x="0" y="122"/>
        </build-position>
        <build-position name="turret-entrance-expansion" width="2" height="2">
          <position x="14" y="97"/>
        </build-position>
      </standard-building-placement>
    </starting-position>
    <starting-position expansion-id="9 oclock" >
      <standard-building-placement>
        <build-position name="non-producting-3X2" width="3" height="2">
          <position x="125" y="42"/>
          <position x="121" y="42"/>
          <position x="125" y="40"/>
          <position x="121" y="40"/>
          <position x="125" y="38"/>
          <position x="121" y="38"/>
          <position x="125" y="36"/>
          <position x="121" y="36"/>
          <position x="125" y="34"/>
          <position x="121" y="34"/>
          <position x="125" y="32"/>
          <position x="121" y="32"/>
          <position x="125" y="30"/>
          <position x="121" y="30"/>
          <position x="118" y="40"/>
          <position x="118" y="38"/>
          <position x="118" y="36"/>
          <position x="118" y="34"/>
          <position x="118" y="32"/>
          <position x="114" y="36"/>
          <position x="114" y="34"/>
          <position x="114" y="32"/>
          <position x="114" y="29"/>
          <position x="117" y="29"/>
        </build-position>
        <build-position name="barracks" width="4" height="3" shortcut="BB">
          <position x="112"  y="61"/>
          <position x="116" y="61"/>
          <position x="120" y="61"/>
          <position x="112" y="58"/>
          <position x="116"  y="58"/>
          <position x="120" y="58"/>
        </build-position>
        <build-position name="natural-expansion" width="4" height="3" shortcut="Ex">
          <position x="116" y="75"/>
        </build-position>        
        <build-position name="engineering-bay" width="4" height="3" shortcut="BE">
          <position x="113" y="38"/>
        </build-position>      
        <build-position name="refinery" width="4" height="2" shortcut="BR">
          <position x="116" y="42"/>
        </build-position>
        <build-position name="academy" width="3" height="2">
          <position x="111" y="34"/>
        </build-position>
        <build-position name="turret-entrance-expansion" width="2" height="2">
          <position x="108" y="77"/>
        </build-position>  
      </standard-building-placement>
    </starting-position>
  </starting-positions>
</map-description>
